### ISSUE TITLE
AbstractController Error, Action Not Found

### ISSUE THREAD

**Issue by mikejmorgan** [ankane/ahoy_email#103]
When the GET request starts on the pixel, I get this error:
`Started GET "/ahoy/messages/KXCF68eFVLbvGMayNA3XXW97RqtTclbt/open.gif" for 68.249.236.106 at 2018-04-21 16:34:38 -0500

AbstractController::ActionNotFound (The action 'KXCF68eFVLbvGMayNA3XXW97RqtTclbt' could not be found for Ahoy::MessagesController):`
The route appears to be correct in rake routes.

**Comment by ankane** [comment]
Hey @mikejmorgan, my guess is another route in your app is interfering. I don't think it's an issue with the gem.
