### ISSUE TITLE
Ahoy Email 1.0

### ISSUE THREAD

**Issue by ankane** [ankane/ahoy_email#104]
Breaking

- [x] Only enable history of messages by default
- [x] Only support Rails 4.2+
- [x] Only create Ahoy::Message record when sent (move tracking to interceptor)
- [x] Move to HMAC-SHA256

Possibly

- [x] Use `heuristic_parse` by default and remove option

Next major release

- [ ] Remove current method of open and click tracking for user privacy. Figure out a way to provide open and click rates without compromising privacy, like using a random token that is not saved anywhere. Apps can store the set of tokens that open and click to compute open and click rates, but won’t know exactly who the users are. Need to filter token from message body if stored.

Possibly, non-breaking

- [x] Add configurable `track_method` option
- [ ] Use `configure` block to populate `default_options`
- [ ] Add Mongoid generator
- [ ] Change user_id and user_type to recipient_id and recipient_type for new installs
- [ ] Use array for `to` column in Postgres for new installs
- [ ] Add ability to limit emails (only send once per user)
- [x] Improve tests

**Comment by luizeof** [comment]
can we save message_id on ahoy_messages table?

**Comment by ankane** [comment]
Released
