### ISSUE TITLE
Configure Mongoid or Active Records

### ISSUE THREAD

**Issue by coderhs** [ankane/ahoy_email#112]
Making the same system work for mongoid is as simple as changing the configuration in the model files. So we can make the system configurable to choose between the two.

Any suggestions on the right approach for this? we can have settings placed in an initializer to choose mongoid, and if nothing is defined go with active records.

**Comment by ankane** [comment]
Hey @coderhs, I added instructions for Mongoid. https://github.com/ankane/ahoy_email#mongoid

You'll need to be on Ahoy Email 1.0+.
