### ISSUE TITLE
NoMethodError attr_accessor Mail::Message:Class when updating to 1.0.1

### ISSUE THREAD

**Issue by mbodlund** [ankane/ahoy_email#114]
Updated from 1.0.0 to 1.0.1 and when sending mails I get

NoMethodError (private method `attr_accessor' called for Mail::Message:Class):

This happens even if I AhoyEmail.default_options[:message] = false

**Comment by mbodlund** [comment]
In v 1.0.0
> UtilityMailer.with(to: 'test@domain.com')
=> #<ActionMailer::Parameterized::Mailer:0x00007fe28edc1608 @mailer=UtilityMailer, @params={:to=>"test@domain.com"}>

In v 1.0.1
>  UtilityMailer.with(to: 'test@domain.com')
NoMethodError: private method `attr_accessor' called for Mail::Message:Class

**Comment by ankane** [comment]
Hey @mbodlund, thanks for reporting 👍 Looks like that method is private in earlier versions of Ruby. Fixed on master.

**Comment by mbodlund** [comment]
Super - thx. Sorry for leaving out the Ruby version. Was a bit short on time yesterday.
