### ISSUE TITLE
HTML style changes

### ISSUE THREAD

**Issue by Hamdan85** [ankane/ahoy_email#118]
Hi @ankane ...

Firstly, I would like to thank you for the amazing work to the comunity that you are doing. Im amazed of how many gems of yours I'm using, and they are always excelent. Im deeply grateful.

I would like to report that I'm suffering from an issue. Im using ahoy_email to track some behaviors and using subscribers to trigger some actions in that attends my business rules.

But for some reason that I cant explain, some of the styling embeded on this template (that is stored on DB and called programatically) is corrrupted when the ahoy_email is active. 

I have absolutely no clue of how to proceed in this matter because your gem is a very important part of the system lol...

Do you can imagine some reason for my HTML being changed???
again, the design works perfectly without ahoy_email.

in my mailer:
```ruby 
track user: @employee
mail from: @company.email_sender,
         to: "#{@employee.name} <#{@employee.email}>",
         subject: @company.caught_email_title do |format|
      format.html { render text: @template }
end
```

**Comment by Hamdan85** [comment]
Im sorry for that @ankane ... 
My gem was outdated.

Closing the issue!

**Comment by Hamdan85** [comment]
@ankane, actually I have updated the gem but didnt observed the new initialization methods, so it wasnt actually running.

Now that I did, I still has the same problem... some styles are being ignored...
is there some html parsing that I need to be aware of? 

heres a failure html example:
[failure.txt](https://github.com/ankane/ahoy_email/files/2564399/failure.txt)

**Comment by ankane** [comment]
Hey @Hamdan85, unfortunately, I don’t have the bandwidth to provide support through GitHub Issues. If you think you’ve found an issue, try to understand exactly what changes with the CSS, why that throws off Gmail and not the others, and come up with minimal steps to reproduce. Once you do that, report back.

**Comment by Hamdan85** [comment]
Ok Andrew, thanks in advance.... Will do.

Em sex, 9 de nov de 2018 03:04, Andrew Kane <notifications@github.com>
escreveu:

**Comment by Hamdan85** [comment]
@ankane I didnt understood what EXACTLY messes with the CSS, but I'm sure that it happens when you are reprocessing the HTML with Nokogiri inside the track_links methods in processor.rb (is not that I'm lazy, but it's very hard to diff a huge styled email html  in the eye).

So, I had a hint that something was messing with inlining and choosed to reprocess it entirely with Roadie Gem... Success... everything works perfectly now..

So, my suggestions is to include RoadieGem to the method and process it.
Im making a pull request in a few minutes. Hope to help.
