### ISSUE TITLE
Open Tracking

### ISSUE THREAD

**Issue by thejazz15** [ankane/ahoy_email#130]
Currently opens get tracked regardless of who opens the email. Is there any possible way where we can track an open only if the recipient of the email opens it?

**Comment by ankane** [comment]
Hey @thejazz15, this isn't possible technically.

**Comment by thejazz15** [comment]
Alright thanks @ankane

**Comment by ACPK** [comment]
@thejazz15 - You could block it from tracking your office's IP address. If this is similar to what you're looking for, let me know!
