### ISSUE TITLE
Can't modify frozen String

### ISSUE THREAD

**Issue by bluengreen** [ankane/ahoy_email#131]
Looks like this is an issue in the ahoy_mail package as well. 

https://github.com/ankane/mailkick/pull/21

I'm seeing "Can't modify frozen String" in specs now leading me to here: 

https://github.com/ankane/ahoy_email/blob/master/lib/ahoy_email/processor.rb#L85 

and here 

https://github.com/ankane/ahoy_email/blob/master/lib/ahoy_email/processor.rb#L115

**Comment by ankane** [comment]
Hey @bluengreen, should be fixed on master.

**Comment by bluengreen** [comment]
Thanks!!
