### ISSUE TITLE
Api only application

### ISSUE THREAD

**Issue by prathip111** [ankane/ahoy_email#134]
Hi,
     I am using ahoy email in my rails API only application , and I cant able to track the open and click event. Even record is not created in the ahoy table. I don't know how to debug

Thanks!

**Comment by mike1011** [comment]
Add this in the `initilializers/ahoy_email.rb`

`AhoyEmail.api = true`

and you can read more on the [ReadMe ](https://github.com/ankane/ahoy_email)page...most of the things are clearly mentioned about including  HOWTO about tracking your mailers.

**Comment by ankane** [comment]
Hey @prathip111, please check out the Contribute Guide for where to get help.
