### ISSUE TITLE
Open Tracking  - triggering multiple times?

### ISSUE THREAD

**Issue by emilyadavis303** [ankane/ahoy_email#138]
I'm working to track down an issue we're having with tracking email opens. 

We subscribe to the `open` event via `EmailSubscriber`, and from there create an event record to track the open. I'm seeing an inconsistent issue (dating back to at least early this summer) that seems to be causing this event to trigger multiple times in rapid succession. It varies in number of duplicates from 2 - 86. Unfortunately, I am unable to reproduce this behavior myself.

We subscribe to and track the `click` event in an identical fashion w/o issue. 

Has anyone seen something like this before?

**Comment by ankane** [comment]
Hey @emilyadavis303, I don't use open tracking myself, but will leave this open for a bit to see if others that do have seen it.

**Comment by ankane** [comment]
Cleaning up issues. Please let us know if you find anything.
