### ISSUE TITLE
Filtering false opens

### ISSUE THREAD

**Issue by nitsujri** [ankane/ahoy_email#139]
Hi AhoyEmail team!

Thank you for such a great gem. It's been super helpful in building out our in house email tracking. 

In our email trackings, we're getting very high open rates and learned that it's related to the way GMail displays previews:

https://www.gmass.co/blog/false-opens-in-gmail/

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246 Mozilla/5.0` according to the article.

Is there a way to perform the filtering on this project?

Thanks,
Justin

**Comment by nishankbhati** [comment]
Hello, I have checked it. What I have observed is that gmail fetches mail when notification is turned on (both browser or phone). If notifications are turned off then only it will show true reads which is not of-course a good solution.

**Comment by ankane** [comment]
Hey, sorry for the delay. Open tracking was removed in today's 2.0 release for privacy, but there wasn't previously a way to do filtering.

**Comment by StanBright** [comment]
I have a feeling that the removal of "Open" tracking" will discourage many people to upgrade. 

Anyways, thanks for the great work @ankane.
