### ISSUE TITLE
Use RuboCop?

### ISSUE THREAD

**Issue by utkarsh2102** [ankane/ahoy_email#143]
Hi @ankane,

Thanks for maintaining this (and all the other wonderful gems) so far!
However, there are a bunch of things that could be fixed according to the Ruby style guide.

Would you consider using RuboCop?
I would be happy to raise a PR if so :)

**Comment by ankane** [comment]
Hey @utkarsh2102, thanks for the suggestion. I'm personally not a fan of linting (may put my detailed thoughts into a blog post at some point).

**Comment by utkarsh2102** [comment]
Hiya,

> I'm personally not a fan of linting (may put my detailed thoughts into a blog post at some point).

Oh sure :smile: 
I'd love to read that! \o/

Anyway, thanks for your work! :rocket:
