### ISSUE TITLE
Track utm_params breaks links with nested content

### ISSUE THREAD

**Issue by mnort9** [ankane/ahoy_email#148]
When using `track utm_params: true`, it seems to remove nested link content to outside the link tag. Example:

```
track utm_params: false

<a href="https://google.com">
  <img src="...">
</a>

track utm_params: true

<a href="https://google.com?utm_source=...">
</a>
<img src="...">
```

**Comment by ankane** [comment]
Hey @mnort9, I'd double check that the markup isn't malformed beforehand. If that's not the issue, can you create a test case like the one in the commit above to reproduce?

**Comment by ankane** [comment]
Closing due to no response
