### ISSUE TITLE
Bring back open tracking

### ISSUE THREAD

**Issue by oofdog** [ankane/ahoy_email#153]
Hi,

So the changelog says open tracking was removed due to privacy concerns, but in that case, why does this gem exist at all? Analytics will always be a trade off between privacy and insight.

Instead of making the decision on behalf of everyone, why don't we let the end users decide? Allow us to conditionally enable/disable open tracking based on the user preferences, similar to click tracking with the `if:` parameter.

Thank you

**Comment by ankane** [comment]
Hey @oofdog, it's not something I'd like to support, but you can fork from the latest 1.x version.

**Comment by ugnius-s** [comment]
Having open rate is critical to measure the effectiveness of the campaigns.
