### ISSUE TITLE
Allow redirections to other/external hosts for click event

### ISSUE THREAD

**Issue by kunal-bluebash** [ankane/ahoy_email#154]
**Context**
While tracking mail using ahoy click it redirects user to external url using redirect_to. 

Rails 7 requires to explicitly pass allow_other_host: true to redirect_to to allow such redirections. Otherwise, an ugly exception is raised.

Rails 7.01
**Expected behaviour.**
When using ahoy with Rails 7 and redirecting user to external url, It will successfully redirected to that url.

**Current behaviour.**
When using ahoy with Rails 7 and redirecting user to external url, a ActionController::Redirecting::UnsafeRedirectError is raised.

**Solution:**
We can add allow_other_host: true in this [controller](https://github.com/ankane/ahoy_email/blob/master/app/controllers/ahoy/messages_controller.rb#L36)

**Comment by ankane** [comment]
Hey @kunal-bluebash, thanks for reporting! Just pushed a new release.

**Comment by StanBright** [comment]
... some of us are stuck on v1.1.1 😭

**Comment by BrVer** [comment]
hey, migrating to >= 2.0 is painful for us, we had to postpone this process,
is there any way this fix can be implemented on 1.1 ?
