### ISSUE TITLE
AhoyEmail.stats returning nill

### ISSUE THREAD

**Issue by Splitrox** [ankane/ahoy_email#165]
Hi, AhoyEmail.stats is returning nil on the last version. (2.4.0). Tried on 2.2.0 and seems working what changed exactly?

Also another question i have is if is possible to show this kind of information with ahoy captain
https://github.com/joshmn/ahoy_captain

**Comment by ankane** [comment]
Hi @Splitrox,

1. I'm not sure how to reproduce, but don't think it's an issue with Ahoy Email ([diff](https://github.com/ankane/ahoy_email/compare/v2.2.0...v2.4.0))
2. Yes, someone could create a similar project to show the stats

**Comment by ankane** [comment]
If you add debugging and find an issue, feel free to share or create a PR.
