### ISSUE TITLE
Understanding of Ahoy::Click and relation with Ahoy

### ISSUE THREAD

**Issue by Splitrox** [ankane/ahoy_email#166]
Hi,

Can't seem to understand what is the relation from Ahoy::Click and the rest of Ahoy Classes and how i can use to get valuable feedback. For example, Ahoy works with events, for example $view. Can't see nothing related to events. To create my own event i had to do:
```ruby
class CustomSubscriber < AhoyEmail::DatabaseSubscriber
  def track_send(data)
    super
  end

  def track_click(data)
    super

    ahoy = data[:controller].ahoy

    ahoy.track "$email_click", url: data[:url]
  end

  def stats(campaign)
    super
  end
end
```
And this still contains issues, for example is not relating the view and user id to the actual person so I can't really know where is this coming from and how this click ends at (purchase/form signup). Also it doesnt allow me to pass all of this data related from a specific campaign to a specific event.

Also what is the purpose of Ahoy::Click#token and does it server to relate to any other data? Ahoy::Click class seems empty

Another thing is that it seems i can only know the campaign and not the step related with the click. For example lets imagine I have a campaign for reminding a user about something. I would like to know how many clicks i had on the first step, second and third separately.

**Comment by ankane** [comment]
Hi @Splitrox, click analytics are separate from Ahoy visits/events (and not tied to a specific message/user unless `AhoyEmail.save_token` is set). You can use UTM tagging to track which visits came from a specific email campaign (and Ahoy events / `visitable` to associate purchases/sign ups with visits).

Please use other resources for additional help with this.
