### ISSUE TITLE
How to start work on ahoy_email

### ISSUE THREAD

**Issue by eveerababu-nyros** [ankane/ahoy_email#17]
I followed the same but I could able to migrate and I got table called ahoy_messages and when I send any mail then, fields in the ahoy_messages table were updated, but when I read the mail in gmail/yahoo open_at field is not updating. Can you please say me where were I went wrong

**Comment by abhasg** [comment]
I am facing the same issue, can you please let me know what is the solution?

**Comment by rajrishav0711** [comment]
Following is the invisible pixel link which I get in the email : 

"https://ci6.googleusercontent.com/proxy/yfZleGdcqENev58hqKrGAjPy4TF0FSrbuQTzX4LOe4K5NxMA1JPg14kF7rBEHhSJsXRuyR1Z_DL6ZwExp6e1CcSWQjJGsFCNtIqW5OEqKMRpDrRy1k9PjI7aNYYDiouEBGXWgnR3Xg=s0-d-e1-ft#http://192.168.1.158:3000/ahoy/messages/HuMrA0D3Xs6IuCcakFLN4qpZS3ZNmBwH/open.gif"

This link doesn't open, and thats the reason for opened_at not getting updated. Can you tell whats the solution?

**Comment by ankane** [comment]
@rajrishav0711 Google proxies content for privacy reasons. `192.168.1.158` is a local IP, which is unreachable by Google.  You'll need to configure your email to use a program like ngrok to get around this. https://ngrok.com/

**Comment by rajrishav0711** [comment]
@ankane : Thanks. I tried on my staging app, now I get the following error on opening any email

"(No route matches [GET] "/ahoy/messages/48oZwgN8KzH6o5Weis75KxQ4sKjP0WAj/click")" 

which I don't get on my local. Entries are getting populated properly on my local.

**Comment by ankane** [comment]
Cleaning up issues. Please reopen if there's additional information.
