### ISSUE TITLE
email tracking on cc and bcc

### ISSUE THREAD

**Issue by guyisra** [ankane/ahoy_email#18]
Hey,

great gem!

how does that tracking (view and open) work with CC and BCC emails? 
does it check who opened/clicked or it doesn't care?

**Comment by dlackty** [comment]
@guyisra It just doesn't care.

**Comment by ankane** [comment]
@guyisra it's not possible to differentiate between recipients when using CC or BCC.  If you need this, you should send separate emails to each recipient.
