### ISSUE TITLE
TypeError (can't convert nil into String)

### ISSUE THREAD

**Issue by pdoggi** [ankane/ahoy_email#24]
I'm getting a `TypeError (can't convert nil into String):` in line 3 below.  I checked to make sure that `user.email` is not nil, so it isn't that. The Ruby error isn't very helpful so not sure how to proceed.  Is there something I need to pass into the mail method?  
```ruby
class UserMailer < ActionMailer::Base
  def send_welcome_email(user)
	mail(:to => user.email, :subject => "Welcome!")
  end
end
```

**Comment by pdoggi** [comment]
Is this related to #15 ?  I just ran `AhoyEmail.secret_token` in rails console and it came up `nil`.  I'm using Rails 4.0.2 and ahoy_email 0.2.2.  I'll try to set the token in the initializer and see if that fixes my error.

**Comment by pdoggi** [comment]
Adding the following to my initializer did not help.
```ruby
AhoyEmail.secret_token = SECRET_HASH
#or, I tried both
AhoyEmail.options[:secret_token] = SECRET_HASH
```
However, when I add `AhoyEmail.secret_token = SECRET_HASH` right before the `mail` method below. I no longer get the error, so I think this is related to #15.  

```ruby
class UserMailer < ActionMailer::Base
  def send_welcome_email(user)
    AhoyEmail.secret_token = SECRET_HASH
    mail(:to => user.email, :subject => "Welcome!")
  end
end
```
Any help will be much appreciated.  I like the gem concept and haven't found any alternatives. Thanks!

P.S. I'm running Rails 4.0.2 and ahoy_email 0.2.2.  If you need any other information, let me know. Thanks!

**Comment by ankane** [comment]
Hey @pdoggi, if you point to the master branch in your Gemfile, the initializer solution will now work.

In your Gemfile:

```ruby
gem 'ahoy_email', github: 'ankane/ahoy_email'
```

and the initializer

```ruby
AhoyEmail.secret_token = SECRET_HASH
```

**Comment by pdoggi** [comment]
Awesome, thanks for the quick fix! It works fine now.

**Comment by abrambailey** [comment]
Where specifically should I put `AhoyEmail.secret_token = SECRET_HASH`
