### ISSUE TITLE
NoMethodError (undefined method `ahoy' for #<Ahoy::MessagesController:0x6a21608>)

### ISSUE THREAD

**Issue by pdoggi** [ankane/ahoy_email#25]
I'm getting this undefined method `ahoy` in line 5 below in my initializer. The database actually records the opened_at timestamp fine, so I'm good with the functionality.  Just thought I'd report this error I found in my server log.  Let me know if you need more information.

```ruby
class EmailSubscriber

  def open(event)
    # :message and :controller keys
    ahoy = event[:controller].ahoy
    ahoy.track "Email opened", message_id: event[:message].id
  end

  def click(event)
    # same keys as above, plus :url
    ahoy = event[:controller].ahoy
    ahoy.track "Email clicked", message_id: event[:message].id, url: event[:url]
  end

end

AhoyEmail.subscribers << EmailSubscriber.new
```

**Comment by ankane** [comment]
You'll need to install [Ahoy](https://github.com/ankane/ahoy) to use that code.

**Comment by pdoggi** [comment]
I see, thanks for the tip! I'll have to check out Ahoy.

**Comment by samuraraujo** [comment]
What does this EmailSubscriber actualy do? Is it needed to track email?

**Comment by pavankat** [comment]
@samuraraujo it's used in conjunction with the ahoy gem to track the email in the database
