### ISSUE TITLE
Work with models other than User

### ISSUE THREAD

**Issue by ollieglass** [ankane/ahoy_email#29]
Could you make this work on any model, not just User?

https://github.com/ankane/mailkick handle this nicely, you just add `mailkick_user` to the model you want it to work on

**Comment by ankane** [comment]
@ollieglass user is polymorphic, so it already supports any user model. https://github.com/ankane/ahoy_email/blob/master/app/models/ahoy/message.rb#L5

**Comment by ollieglass** [comment]
I see... so I say my model (Subscriber) `has_many :messages, as: :user`... and that won't conflict with another model called User?

Won't this line require the model to be called User?

https://github.com/ankane/ahoy_email/blob/6a7d42be3dcafff4863d7ee70515fe6ce2f43d3e/lib/ahoy_email.rb#L24

Sorry if I'm not getting it!

**Comment by CollinGraves** [comment]
@ollieglass that shouldn't be an issue, although the naming of this polymorphic relationship is rather awkward. 

You wonder if something like: `belongs_to :messageable, polymorphic: true` wouldn't be better, in which case you could include a global override to specify the model of your choice. 

I just think it's weird to technically have a `User` class that also has a `"User"` for its `user_type`. :)

**Comment by ankane** [comment]
@ollieglass that's the default `user` option, but you can pass whatever you'd like to `track user: any_user`.

**Comment by codeglover** [comment]
He doesn't want to pick a particular user, he wants to use a different model completely. He is not tracking users, he is tracking subscribers. I too have  a Subscriber model that I wish to track. As mentioned before, mailkick handles this perfectly but I cannot seem to do it with this gem.
