### ISSUE TITLE
Mails are not intercepted

### ISSUE THREAD

**Issue by winston** [ankane/ahoy_email#35]
Hi @ankane!

I have a problem where my mails on Heroku are not being intercepted and hence no `Ahoy::Message` is created everytime I send a mail. It's a Rails 4 app. (It's working on local.)

I am using sendgrid for sending my mails. Will this affect it?
I am also sending my emails as background jobs using suckerpunch.

I do see that the `AhoyEmail::Interceptor` has been registered:

```
irb(main):018:0> Mail.class_variable_get(:@@delivery_interceptors)
=> [AhoyEmail::Interceptor]
```

The mails actually get sent through, and there are no errors. It just seems that the interceptor is not kicking in?

Would you be able to point me in the right direction? Thank you so much!

**Comment by winston** [comment]
Hmm.. I am not sure what happened, but I tried it several times earlier and it didn't work, but as soon as I posted this, it worked all of a sudden... Closing this for now. Sorry for the trouble!

**Comment by ankane** [comment]
No worries, glad it's working!

**Comment by ericraio** [comment]
i'm current'y having this issue, any ideas?

**Comment by rossettistone** [comment]
@ericraio Did you ever get to the bottom of this? I've been having the same issue for two weeks now, and am at a loss. It started happening when I bumped to Rails 5.1, but I don't see any relevant config changes in 5.1 that would have caused the problem.

**Comment by rossettistone** [comment]
The issue seems to have vanished, though I can't seem to credit it to anything. *sigh*
