### ISSUE TITLE
How to get ahoy_email to work with the async deliver_later via ActiveJob?

### ISSUE THREAD

**Issue by siadat** [ankane/ahoy_email#36]
When I call `deliver_now` ahoy email tracks emails and links perfectly. However, when I call `deliver_later` instead, it is not replacing the links with ahoy tracked links. E.g.,

    class NotificationMailer < ApplicationMailer
        def new_message(user:)
            @user = user
            track user: @user
            mail(to: @user.email, subject: 'subject').deliver_later
        end
    end

**Comment by dlackty** [comment]
@siadat From my experience, ahoy_email works fine with ActiveJob and `deliver_later`. There's no need to put `deliver_later` method call in you mailer, and you should just use `NotificationMailer.new_message(user:@user).deliver_later` instead. Could you give a try?

**Comment by ankane** [comment]
Cleaning up issues. 👍  to @dlackty's suggestion.
