### ISSUE TITLE
Sending Mail without Action Mailer

### ISSUE THREAD

**Issue by AnthonyDeSimone** [ankane/ahoy_email#43]
I'm using Campaign Monitor for email, but would like to move the tracking into Rails. Is there an easy way to use Ahoy to generate the tracking data without sending an email from Action Mailer?

**Comment by ankane** [comment]
Hi Anthony, I haven't used Campaign Monitor, but I can't think of a great way to do this. Another approach is to use their tracking and fetch the data through their API.

**Comment by AnthonyDeSimone** [comment]
Yea, I wanted to see if I could move outside of their API for tracking purposes. I'm stuck with them currently for deliverability reasons.

I can send data to CM to be dynamically inserted into a template. The question is can the tracking data that Ahoy creates be decoupled from ActionMailer or is there no easy way of doing that?

**Comment by ankane** [comment]
I haven't tried it before, but you could try using the `Ahoy::Processor` directly.  However, it's an internal API, so you'll need to be a bit careful when upgrading.
