### ISSUE TITLE
mail not being intercepted

### ISSUE THREAD

**Issue by ericraio** [ankane/ahoy_email#46]
@ankane 
When I test this locally, ahoy email is being intercepted however when I send a test email in the production environment,  rails and/or ahoy email is not processing the interceptor.

**Comment by mool** [comment]
I'm having the same problem? @ericraio how did you fix it?

**Comment by mool** [comment]
I found the problem, I had to set "config.action_mailer.default_url_options" in config/environment/production.rb and started to work.
