### ISSUE TITLE
Possible to store referring message id?

### ISSUE THREAD

**Issue by oshields** [ankane/ahoy_email#48]
Hello,
First off, I've really loved working with this gem!  I have a use case where it would be helpful to persist information about the referring email message (in a cookie or session variable).  Essentially when a user clicks a link they are taken to an article.  If a user tries to comment / interact with that article, I would like to show the login modal and have their email already filled in.  This removes friction from the login process.  I'm planning on monkey patching the message_controller to store the referring message id in a cookie or something, but was wondering if there is a better solution or if this is somehow built in.  Thanks for any advice!

UPDATE:
This is where I'm at ... in intializers/ahoy.rb I patch the MessagesController class to store the email in the session.  Then when the user attempts to comment or login, I auto populate the email as session[:login_email_suggestion]    This functionality works especially well if the user hasn't visited the site in a while and doesn't remember their login email.
```
Ahoy::MessagesController.class_eval do
  def set_message
    @message = AhoyEmail.message_model.where(token: params[:id]).first
    session[:login_email_suggestion] = @message.try(:to)
  end
end
```

**Comment by ankane** [comment]
Hey @oshields, another approach is to embed their email address in the original link. Your method should work as well.
