### ISSUE TITLE
All routes lead to root path

### ISSUE THREAD

**Issue by abrambailey** [ankane/ahoy_email#59]
Here's the link that is supposed to go to our Facebook page. After clicking the link the user is just directed to our root path. Not sure what's going on exactly.

```
http://qa.hearingtracker.com/ahoy/messages/Knji6paAcoXzj4rk6tMn2QLrll4mLKbL/click?signature=d51042bea2a504a86573290b590910ef5dfc8ab1&url=https%253A%252F%252Fwww.facebook.com%252Fhearingtracker%252F%253Futm_campaign%253Dsignup_confirmation%2526utm_medium%253Demail%2526utm_source%253Duser_mailer
```

**Comment by ankane** [comment]
Hey Abram, don't be afraid to dive into the code to figure out what's up - it's one of the best parts about open source.  [Looking here](https://github.com/ankane/ahoy_email/blob/master/app/controllers/ahoy/messages_controller.rb#L23), you can see the signature is failing to validate.  Be sure your `secret_token` is the same on the server that sends the emails and the server that tracks clicks.

**Comment by abrambailey** [comment]
Oh hey thanks for the response @ankane ... Weird as the email is generated on the production server and tracked by the production server. I am using the `secrets.yml` file in my app. Everything works well in development. Do I need to put `AhoyEmail.secret_token = SECRET_HASH` in the initializer, or do anything else to avoid this problem?

**Comment by ankane** [comment]
`secret_token` should be set automatically. If the config is consistent on the servers that send the emails and the servers that track the clicks, it should just work.

**Comment by hesiod-au** [comment]
This is a year late for abrambailey, but I had the same issue, it was being caused by the prod server having automatic redirects from http to https. If the email has the host set to http then the link is processed from the redirected https link, the hashes won't match.

Setting the host to https in production.rb did the trick:
config.action_mailer.default_url_options = { :host => "https://www.xxxx.xxxx" }

**Comment by ankane** [comment]
Thanks for sharing @hesiod-au 👍
