### ISSUE TITLE
Can you reference Ahoy::Message properties from email template? i.e. token?

### ISSUE THREAD

**Issue by ttilberg** [ankane/ahoy_email#64]
Sorry, this isn't much of an issue -- but I'm trying to figure out if I am able to reference some of the auto-generated items that are tracked by Ahoy in the email template.

For example, I want to include the generated Ahoy::Message.token as a link parameter as part of an invitation scheme. Are these properties accessible somehow in the email templates?

**Comment by ankane** [comment]
Hey @ttilberg, there's not a currently a way, but I'm happy to accept a PR for it. I don't think it'd be too difficult to add.

**Comment by ankane** [comment]
Planning to move to an interceptor for 1.0, so don't think this will be possible. For future readers, for an invitation scheme, I'd recommend an approach that's decoupled from Ahoy Email.
