### ISSUE TITLE
How to use Ahoy_Email links in Rspec tests

### ISSUE THREAD

**Issue by helphop** [ankane/ahoy_email#66]
I test my emails to see if they contain specific links.  Now with the ahoy_email gem the links that get generated contain all of the tracking parameters so my tests fail.

How can I generate those links with the parameters in my Rspec tests so the tests will work.

Example:

```
it "has a link to the quotation request show page" do

  #setup
  proofreader = create(:employee)
  quotation_request = create(:quotation_request)

  #exercise
  email = EmployeeMailer.quotation_request_notification(quotation_request, proofreader)

  #verification
  expect(email.text_part.body.to_s).to include(quotation_request_url(quotation_request))
  expect(email.html_part.body.to_s).to include(quotation_request_url(quotation_request))

end
```

This fails because within Rspec ahoy_email is not generating the URL with the extra parameters for tracking.

How can I get ahoy_email to work inside of Rspec tests?

**Comment by kyleschmolze** [comment]
I just disable AhoyEmail entirely in Rspec by adding this to my spec_helper.rb:

```
  AhoyEmail.track message: false
```

**Comment by ankane** [comment]
Thanks for another assist @kyleschmolze
