### ISSUE TITLE
Using Rails mailer previews creates entries in ahoy_messages

### ISSUE THREAD

**Issue by cannikin** [ankane/ahoy_email#72]
Has anyone else seen Rails' mailer previews creating entries in the `ahoy_messages` table? We're actually seeing two entries created for every preview, I believe because of the way mailers are presented in frames—one frame contains the header preview at the top, the other contains the HTML view of the email itself below.

I don't think we're doing anything custom with mailers, previewers or ahoy. And I don't see any other issues mentioning this phenomenon. Am I missing something simple?

We're running Rails 5.0.0.1 and ahoy_email 0.4.0.

**Comment by JustinasDaugela** [comment]
@cannikin I just added ahoy_email to my codebase and it tracks previews (two times) for me as well.  Doesn't seem like a big issue, since we're only using previews locally.

**Comment by cannikin** [comment]
Yeah we're only previewing locally as well, but we put real users into the preview and then when we view their message history later it looks like they've been sent dozens and dozens of additional messages, when really they were just preview views. :(

**Comment by ankane** [comment]
FWIW, you can query on the `sent_at` field to remove emails that were never sent.
