### ISSUE TITLE
Signature matching fails for mails opened on old browsers

### ISSUE THREAD

**Issue by harshvardhansharma** [ankane/ahoy_email#73]
This is happening in case of old browsers - IE and Safari 6. Exact issue being these browsers decode the '%26' as '&' in the redirection url, thus making query params out of the entire url for the original ahoy's url.

Example :
`https://mydomain.com/ahoy/messages/jww7AmF2DPiz7oZeEGTs7wYJTEWKbm2d/click?signature=5296552ddad41b20b465c2764ab607caa35946cb&url=https%3A%2F%2Famazingapp.com%2Fapp%3Fend_date%3D2016-11-01%26base_date%3D2015-11-01`

Above url being correct is returned as
`https://mydomain.com/ahoy/messages/jww7AmF2DPiz7oZeRtTs7wYJTEWKbm2d/click?signature=5296552ddad41b20b465c2764aba57caa35946cb&url=https%3A%2F%2Famazingapp.com%2Fapp?end_date=2016-11-01&base_date=2015-11-01`

**Comment by ankane** [comment]
Hey @harshvardhansharma, sorry for the delay. I was never able to reproduce.
