### ISSUE TITLE
opened_at not getting captured

### ISSUE THREAD

**Issue by ThePraveen** [ankane/ahoy_email#74]
https://ci3.googleusercontent.com/proxy/TTlkSFBY45-0rI8TyjufmWqnUFZj-bSAanInnq-sEBEy6nFas97CI0gFO3mjwj_8v9mJESz8aEWfFEBWJl59ZPZx29kV-Qb_nYmqccy0cMVkcInPStVZIqIlJReM4lnxfD87=s0-d-e1-ft#https://www.awign.com/ahoy/messages/OLUnbVMsHJSYX6Cvkw9lEu8gg0DsTlVp/open.gif

this is not present in the googleusercontent and hence not redirecting to my server.

**Comment by kyleschmolze** [comment]
That's Google caching the image, which breaks open tracking (for every service that tries to use an image to track opens).

**Comment by ankane** [comment]
Thanks again @kyleschmolze
