### ISSUE TITLE
Routes issue: Unable to access /ahoy/*

### ISSUE THREAD

**Issue by ACPK** [ankane/ahoy_email#76]
Do I need to place anything in config/routes.rb to get the gem working with Rails5?

All of the links generated by ahoy_email go to 404. Additionally, the 1px by 1px tracing image used for tracking if an email was open doesn't load.

**Comment by osuarez1** [comment]
I had the same issue and solve it by adding the following to config/routes.rb
```
unless respond_to?(:has_named_route?) && has_named_route?("ahoy_email_engine")
    mount AhoyEmail::Engine => "/ahoy"
end
```
I had extracted this from https://github.com/ankane/ahoy_email/blob/master/config/routes.rb
