### ISSUE TITLE
Emails marked as spam because of click tracking

### ISSUE THREAD

**Issue by gdpelican** [ankane/ahoy_email#79]
It appears the approach taken in ahoy emails for tracking email clicks is driving up our spam score, due to it being a phishing technique to mask and redirect to the intended target of the link.

Has anyone else experienced this?

More details on the reported issue here:
https://github.com/loomio/loomio/issues/4022

**Comment by ankane** [comment]
Hey @gdpelican, thanks for reporting 👍  Most email services do this. Are you seeing different spam scores with other services?

**Comment by ankane** [comment]
Cleaning up stale issues
