### ISSUE TITLE
Tracking non-user recipients

### ISSUE THREAD

**Issue by ewhitten** [ankane/ahoy_email#81]
In our use case, we're looking to track all people who opened an email, some of which may not have corresponding user accounts in our system (i.e. the billing contact address is a non-user).  Is this still feasible with ahoy_email?  It seems like a great gem! 

Thanks.

**Comment by kyleschmolze** [comment]
This gem tracks all emails sent, and only attaches a user to the email if it finds a user. So yes, it would work fine.

**Comment by ankane** [comment]
Thanks for the assist @kyleschmolze
