### ISSUE TITLE
Track clicked links also in Mixpanel.

### ISSUE THREAD

**Issue by BLauris** [ankane/ahoy_email#82]
Hello,

First of all, I want to say that this gem works great I am able to track clicked links in e-mails and now I need to see these `clicks` also inside `Mixpanel`. 

To make that happen I need to pass some custom params to redirect URL that is processed inside gem, so afterward I could so something like https://mixpanel.com/help/questions/articles/how-can-i-track-the-links-included-inside-my-mixpanel-email-notifications

Or maybe a way to send this `click` to `mixpanel` from `messages_controller.rb`, but would require some additional code to your gem.

Is there something that you could suggest?

Thanks.

**Comment by ankane** [comment]
Hey @BLauris, you can use events to take an action after a click. https://github.com/ankane/ahoy_email#events

**Comment by BLauris** [comment]
@ankane Great thank's this was just what I needed.
