### ISSUE TITLE
Failing tests after adding gem.

### ISSUE THREAD

**Issue by BLauris** [ankane/ahoy_email#83]
Hello,

added the gem as it's written in documentation, it works fine, only thing is that now I am randomly getting this error in tests:

```
ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

**Comment by BLauris** [comment]
I have got so far that I know this error is raised here:
```
https://github.com/ankane/ahoy_email/blob/master/lib/ahoy_email.rb#L44
```
on `::Ahoy::Message`, but I still don't get why, could you guys help me?

**Comment by ankane** [comment]
Hey @BLauris, there's not much I can do help with the info you've given. I'd try getting the full stack trace to see what's going on.

**Comment by ankane** [comment]
Cleaning up stale issues
