### ISSUE TITLE
Different Model

### ISSUE THREAD

**Issue by bezario** [ankane/ahoy_email#87]
Not sure what I'm doing wrong but I keep getting:
`ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column ahoy_messages.person_id does not exist
LINE 1: ...LECT "ahoy_messages".* FROM "ahoy_messages" WHERE "ahoy_mess...`

**Comment by keoghpe** [comment]
@bezario Could you post your code to help reproduce the issue?

**Comment by ankane** [comment]
Clean up stale issues. Thanks for trying to help @keoghpe 👍
