### ISSUE TITLE
error in processor

### ISSUE THREAD

**Issue by Extrapolator214** [ankane/ahoy_email#90]
https://github.com/ankane/ahoy_email/blob/master/lib/ahoy_email/processor.rb#L106
```
params = uri.query_values(Array) || []
```

`uri.query_values` accepts only hash, not a class. Because of this, any email containing links with params throws an error `TypeError - no implicit conversion of Class into Hash`
It seems like a critical bug, unless I'm missing something.

**Comment by Extrapolator214** [comment]
actually I had addressable 2.2.8, the error is fixed after updating to 2.5. Probably it's worth updating addressable dependency though :)

**Comment by ankane** [comment]
@Extrapolator214 thanks for reporting 👍  Master now specifies a min version (2.3.2).
