### ISSUE TITLE
Setting an email not to send via ActionMailer::Base#perform_deliveries still records an ahoy_messages record

### ISSUE THREAD

**Issue by cannikin** [ankane/ahoy_email#91]
In our Rails app we've got a Mailer Interceptor https://wearestac.com/blog/action-mailer-interceptors that prevents certain emails from being sent (like when their subscription expires, they should receive certain notifications any more). The mailers will be invoked as usual in the app, but the interceptor will cancel the delivery at the last moment if certain conditions are met.

Expected behavior: the email isn't sent and an `ahoy_messages` entry is *not* created in the database

Actual behavior: The email isn't being sent, but an `ahoy_messages` entry *is* created in the database.

**Comment by ankane** [comment]
Hey @cannikin, if your custom interceptor intercepts before it reaches the Ahoy interceptor, you can use the `sent_at` column to tell if the message was actually sent.

**Comment by cannikin** [comment]
@ankane Hmm...in our database I'm still seeing a `sent_at` for all of these emails...

**Comment by cannikin** [comment]
Nope, doesn't like that... complains about Ahoy::Message not existing...something about the order things are initialized doesn't work so well with Engines maybe?

**Comment by ankane** [comment]
Hey @cannikin, looks like you can unregister interceptors. https://github.com/rails/rails/pull/18446

I'd try doing that an re-registering after your own interceptor.

**Comment by ankane** [comment]
Cleaning up stale issues
