### ISSUE TITLE
If Ahoy.exclude_method is defined in ApplicationController ahoy_email will throw an error

### ISSUE THREAD

**Issue by benreyn** [ankane/ahoy_email#97]
Example... 
```ruby
Ahoy.exclude_method = lambda do |controller, request|
  controller.exclude_from_tracking?
end

class ApplicationController < ActionController::Base
  def exclude_from_tracking?
    current_user.admin?
  end
end
```
Will lead to... `NoMethodError: [safely] undefined method `exclude_from_tracking?' for #<Ahoy::MessagesController:...>`

I believe this is because `Ahoy::MessagesController` inherits directly from `ActionController::Base` and not `ApplicationController`

**Comment by ankane** [comment]
Fixed by #98
